version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    build:
      context: frontend
    restart: always
    volumes:
      - "./frontend/resources:/app/resources"
  watcher:
    build:
      context: watcher
    restart: always
    volumes:
      - "./watcher:/app/watch"
      - "./logs/watcher:/app/logs"
  stt_en:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.en
    restart: always
    volumes:
      - "./logs/stt_en:/opt/logs"
  tts:
    build:
      context: tts
      dockerfile: Dockerfile.marytts
    restart: always
 